#!/usr/bin/env bash
set -Eeuo pipefail

init() {
    export BAT_THEME="${BAT_THEME:-ansi}"
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
    GROLES_CONFIG_HOME="${GROLES_CONFIG_HOME:-"${XDG_CONFIG_HOME}/groles"}"
    mkdir -p "${GROLES_CONFIG_HOME}"
    ROLES_JSON="${GROLES_CONFIG_HOME}/roles.json"
    GROLES_REPO="${GROLES_REPO:-"pcrock-thmdo/flyscrape-test"}"
}

curl_download() {
    local url="${1}"
    curl \
        --proto '=https' \
        --tlsv1.2 \
        --silent \
        --show-error \
        --fail \
        --location "${url}"
}

github_latest_tag() {
    local repo="${1}"
    curl_download "https://api.github.com/repos/${repo}/releases/latest" \
        | grep --perl-regexp --only-matching '(?<="tag_name":)\s*"\S+"' \
        | tr --delete '" '
}

update_roles_json() {
    echo "Updating roles data..." >&2
    local latest_tag
    latest_tag="$(github_latest_tag "${GROLES_REPO}")"
    curl_download "https://github.com/${GROLES_REPO}/releases/download/${latest_tag}/roles.json" \
        > "${ROLES_JSON}"
}

get_roles() {
    # shellcheck shell=sh
    # the source of this function will be used inside fzf, executed by `sh` as well as `bash`
    jq '.[0].data.roles' < "${ROLES_JSON}"
}

get_headings() {
    get_roles | jq --raw-output 'map(.title + " (" + .id + ")") | join("\n")'
}

get_details() {
    # shellcheck shell=sh
    # the source of this function will be used inside fzf, executed by `sh` as well as `bash`
    local role_heading="${*}" jq_script role_id
    role_id="$(echo "${role_heading}" | grep --only-matching --perl-regexp '\(\S+\)')"
    jq_script="$(cat <<EOF
map(
    select(("(" + .id + ")") == "${role_id}")
)
| map(
    [
        "# " + .title,
        "",
        "\`" + .id + "\`",
        "",
        "> " + .description,
        "",
        "Beta: \`" + (.is_beta | tostring) + "\`",
        "",
        "Permissions:",
        "",
        (.permissions | map("* \`" + . + "\`") | join("\n"))
    ] | join("\n")
)
| join("\n")
EOF
)"
    jq --raw-output "${jq_script}"
}

select_role() {
    local preview_cmd
    preview_cmd="
ROLES_JSON=${ROLES_JSON}
$(declare -f get_roles)
$(declare -f get_details)
get_roles \
| get_details {} \
| bat --language markdown \
  --wrap character \
  --decorations never \
  --color always \
  --paging never \
  --terminal-width \"\$((FZF_PREVIEW_COLUMNS-2))\"
"

    get_headings | fzf_ui
}

fzf_ui() {
    # expects output of `get_headings` to be piped as stdin
    # returns the user's selected role heading via stdout
    SHELL="sh" \
    fzf --ansi \
        --preview "${preview_cmd}" \
        --preview-window up,75% \
        --layout reverse \
        --prompt "Role: "
}

main() {
    init
    test -f "${ROLES_JSON}" || update_roles_json
    local role_heading
    role_heading="$(select_role)"
    get_roles | get_details "${role_heading}" \
        | bat --language markdown \
          --wrap character \
          --decorations never
}

main
